# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "kz_2018_discount15" # use this to keep track of runs with different settings

scenario:
  simpl: ['']
  ll: ['v1.0']
  opts: [RES0.2-1H, RES0.25-1H, RES0.3-1H]

snapshots:
  start: "2018-01-01"
  end: "2019-01-01"

load_options:
  weather_year: 2018  # Load scenarios available with different weather year (different renewable potentials)

electricity:
  extendable_carriers:
    Generator: [solar, onwind, offwind-ac, offwind-dc]
    Store: [battery, H2]

atlite:
  cutouts:
    asia-2018-era5:

renewable:
  onwind:
    cutout: asia-2018-era5
  offwind-ac:
    cutout: asia-2018-era5
  offwind-dc:
    cutout: asia-2018-era5
  solar:
    cutout: asia-2018-era5
  hydro:
    cutout: asia-2018-era5
    normalization:
      year: 2018

costs:
  fill_values:
    discount rate: 0.15

